import React from "react";
import { SummaryCards } from "./components/SummaryCards";
import { SubjectChart } from "./components/SubjectChart";
import { TestScoresTable } from "./components/TestScoresTable";

export function StudentProgressPDF({ student, summary, appState, reportType, reportMonth }) {
  if (!student || !summary) return null;

  const batch = appState.batches.find(b => b.id === student.batchId);
  const coachingName = appState.settings?.coachingName || "Coaching Center";

  // Calculate batch rank if possible
  let rank = "N/A";
  let batchStats = null;
  if (batch) {
    const batchStudents = appState.students.filter(s => s.batchId === batch.id);
    if (batchStudents.length > 0) {
      // Very basic rank calculation based on overallAverage (if we have access to all tests for batch)
      // For this report, we'll mock it if not available, or just say N/A
    }
  }

  // Get current date formatted
  const reportDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const formattedMonth = reportMonth ? new Date(reportMonth + "-01").toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }) : "";
  const titleText = reportType === "monthly"
    ? `Monthly Progress Report ${formattedMonth ? `(${formattedMonth})` : ''}`
    : "Overall Progress Report";

  return (
    <div
      id={`pdf-report-template-${student.id}`}
      className="bg-[#ffffff]"
      style={{ width: '800px', minHeight: '1131px', padding: '40px', color: '#0f172a' }}
    >
      <style>{`
        #pdf-report-template-${student.id} *, 
        #pdf-report-template-${student.id} ::before, 
        #pdf-report-template-${student.id} ::after {
          border-color: #e2e8f0 !important;
          outline-color: transparent !important;
          box-shadow: none !important;
        }
      `}</style>
      {/* Header section */}
      <div className="flex justify-between items-end border-b-2 border-[#1e3a8a] pb-3 mb-4">
        <div>
          <h1 className="text-2xl font-bold text-[#1e3a8a] mb-1">{coachingName}</h1>
          <h2 className="text-lg font-semibold text-[#475569]">{titleText}</h2>
        </div>
        <div className="text-right text-sm text-[#64748b]">
          <p>Report Date: <span className="font-medium text-[#334155]">{reportDate}</span></p>
          <p>Generated by Kishan Classes Realtime System</p>
        </div>
      </div>

      {/* Student Details Grid */}
      <div className="grid grid-cols-2 gap-3 bg-[#f8fafc] p-3 rounded-2xl border border-[#f1f5f9] mb-4">
        <div>
          <p className="text-sm text-[#64748b]">Student Name</p>
          <p className="text-lg font-bold text-[#1e293b]">{student.fullName}</p>
        </div>
        <div>
          <p className="text-sm text-[#64748b]">Student ID</p>
          <p className="text-lg font-bold text-[#1e293b]">{student.studentId}</p>
        </div>
        <div>
          <p className="text-sm text-[#64748b]">Class / Batch</p>
          <p className="text-base font-semibold text-[#334155]">{student.classGrade} {batch ? `• ${batch.name}` : ''}</p>
        </div>
        <div>
          <p className="text-sm text-[#64748b]">Parent Name</p>
          <p className="text-base font-semibold text-[#334155]">{student.fatherName || student.motherName || "N/A"}</p>
        </div>
      </div>

      {/* Analytics Summary */}
      <SummaryCards summary={summary} rank={rank} />

      {/* Charts & Summary Section 1 */}
      <div className="grid grid-cols-2 gap-4 mb-4">
        <SubjectChart subjectStats={summary.subjectStats} />

        {/* Remarks / Strengths & Weaknesses (Replaces Pie Chart) */}
        <div className="bg-[#f8fafc] p-4 rounded-2xl border border-[#e2e8f0] flex flex-col justify-center h-[220px]">
          <h4 className="font-semibold text-[#1e293b] mb-2 text-base">Academic Analysis</h4>
          <div className="space-y-3 text-sm text-[#475569]">
            <p>
              <span className="font-semibold text-[#047857]">Strengths:</span> {student.fullName} is performing best in
              <span className="font-bold"> {summary.strongest ? summary.strongest.subject : "N/A"}</span>
              {summary.strongest ? ` with an average of ${summary.strongest.averagePercent}%` : ""}.
            </p>
            <p>
              <span className="font-semibold text-[#be123c]">Areas for Improvement:</span> Focus is needed in
              <span className="font-bold"> {summary.weakest ? summary.weakest.subject : "N/A"}</span>
              {summary.weakest ? ` to improve the current average of ${summary.weakest.averagePercent}%` : ""}.
            </p>
            <p className="italic text-[#64748b] text-xs mt-2">
              "Consistent effort and regular practice will help in achieving even better results."
            </p>
          </div>
        </div>
      </div>

      {/* Charts Section 2 - Replaced with Table */}
      <div className="mb-4">
        <TestScoresTable tests={summary.tests} />
      </div>

      {/* Footer */}
      <div className="mt-auto pt-8 border-t border-[#e2e8f0] flex justify-between items-center text-xs text-[#94a3b8]">
        <p>This is a computer-generated document and does not require a signature.</p>
        <p>Page 1 of 1</p>
      </div>
    </div>
  );
}
