import React from "react";
import { SummaryCards } from "./components/SummaryCards";
import { SubjectChart } from "./components/SubjectChart";
import { ProgressChart } from "./components/ProgressChart";
import { SubjectComparison } from "./components/SubjectComparison";

export function StudentProgressPDF({ student, summary, appState }) {
  if (!student || !summary) return null;

  const batch = appState.batches.find(b => b.id === student.batchId);
  const coachingName = appState.settings?.coachingName || "Coaching Center";
  
  // Calculate batch rank if possible
  let rank = "N/A";
  let batchStats = null;
  if (batch) {
    const batchStudents = appState.students.filter(s => s.batchId === batch.id);
    if (batchStudents.length > 0) {
      // Very basic rank calculation based on overallAverage (if we have access to all tests for batch)
      // For this report, we'll mock it if not available, or just say N/A
    }
  }

  // Get current date formatted
  const reportDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  return (
    <div 
      id={`pdf-report-template-${student.id}`} 
      className="absolute top-0 bg-white" 
      style={{ left: '-9999px', width: '800px', minHeight: '1131px', padding: '40px', color: '#0f172a' }}
    >
      {/* Header section */}
      <div className="flex justify-between items-end border-b-2 border-[#1e3a8a] pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-bold text-[#1e3a8a] mb-1">{coachingName}</h1>
          <h2 className="text-xl font-semibold text-slate-600">Student Progress Report</h2>
        </div>
        <div className="text-right text-sm text-slate-500">
          <p>Report Date: <span className="font-medium text-slate-700">{reportDate}</span></p>
          <p>Generated by CCMS</p>
        </div>
      </div>

      {/* Student Details Grid */}
      <div className="grid grid-cols-2 gap-4 bg-slate-50 p-5 rounded-2xl border border-slate-100 mb-8">
        <div>
          <p className="text-sm text-slate-500">Student Name</p>
          <p className="text-lg font-bold text-slate-800">{student.fullName}</p>
        </div>
        <div>
          <p className="text-sm text-slate-500">Student ID</p>
          <p className="text-lg font-bold text-slate-800">{student.studentId}</p>
        </div>
        <div>
          <p className="text-sm text-slate-500">Class / Batch</p>
          <p className="text-base font-semibold text-slate-700">{student.classGrade} {batch ? `• ${batch.name}` : ''}</p>
        </div>
        <div>
          <p className="text-sm text-slate-500">Parent Name</p>
          <p className="text-base font-semibold text-slate-700">{student.fatherName || student.motherName || "N/A"}</p>
        </div>
      </div>

      {/* Analytics Summary */}
      <SummaryCards summary={summary} rank={rank} />

      {/* Charts Section 1 */}
      <div className="grid grid-cols-2 gap-6 mb-6">
        <SubjectChart subjectStats={summary.subjectStats} />
        <SubjectComparison subjectStats={summary.subjectStats} batchStats={batchStats} />
      </div>

      {/* Charts Section 2 */}
      <div className="mb-8">
        <ProgressChart tests={summary.tests} />
      </div>

      {/* Remarks / Strengths & Weaknesses */}
      <div className="bg-slate-50 p-5 rounded-2xl border border-slate-100 mb-8 page-break-inside-avoid">
        <h4 className="font-semibold text-slate-800 mb-3 text-lg">Academic Analysis</h4>
        <div className="space-y-2 text-sm text-slate-600">
          <p>
            <span className="font-semibold text-emerald-700">Strengths:</span> {student.fullName} is performing best in 
            <span className="font-bold"> {summary.strongest ? summary.strongest.subject : "N/A"}</span> 
            {summary.strongest ? ` with an average of ${summary.strongest.averagePercent}%` : ""}.
          </p>
          <p>
            <span className="font-semibold text-rose-700">Areas for Improvement:</span> Focus is needed in 
            <span className="font-bold"> {summary.weakest ? summary.weakest.subject : "N/A"}</span> 
            {summary.weakest ? ` to improve the current average of ${summary.weakest.averagePercent}%` : ""}.
          </p>
          <p className="mt-4 italic text-slate-500">
            "Consistent effort and regular practice will help in achieving even better results in the upcoming assessments."
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-auto pt-8 border-t border-slate-200 flex justify-between items-center text-xs text-slate-400">
        <p>This is a computer-generated document and does not require a signature.</p>
        <p>Page 1 of 1</p>
      </div>
    </div>
  );
}
